//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskoDesk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLIZAS
    {
        public int poli_id { get; set; }
        public string poli_folio { get; set; }
        public Nullable<System.DateTime> poli_vigencia { get; set; }
    }
}
